# =================================================================
# 📋 EXEMPLE DE CONFIGURATION - FIRMWARE LD2410
# OBJET : Modèle de structure ESPHome multi-capteurs
# MISSION : Illustrer l'organisation modulaire via !include
# NOTE : Ce fichier sert de base pour comprendre l'intégration
#        des radars et des capteurs environnementaux.
# VERSION : 1.0.0 (Snapshot)
# =================================================================

substitutions:
  name: "NOM_DE_VOTRE_ESP"
  idname: "ID_DE_VOTRE_ESP" # "_" est le seul caractère autorisé
  board: esp32dev
  type: esp-idf # arduino
  loglevel: DEBUG # VERY_VERBOSE
  static_ip: 192.168.1.XXX
  ibeacon_uuid: "VOTRE_UUID_IBEACON"
  ibeacon_name: "tricordeur"
  min_rssi: "-71dB"
  sda: "21"
  scl: "22"
  bmeaddress: "0x76"
  offset: "0.0"
  piece: "NOM_DE_LA_PIECE"
  uart_tx: "17"
  uart_rx: "16"
  gpiopin: "04"
  
  # ==========================================
  #   RÉGLAGES DE PERFORMANCE & RAFRAÎCHISSEMENT
  # ==========================================
  # ---> MODE RÉGLAGE (Utilisé pour un tracé fluide lors de la configuration)
  # gate_throttle: 1s
  # energy_throttle: 1s
  #
  # ---> MODE PRODUCTION (Valeurs économes pour ne pas saturer Home Assistant)
  # gate_throttle: 60s
  # energy_throttle: 15s
  # ==========================================

  gate_throttle: 60s
  energy_throttle: 15s
  distance_delta: "10.0"

packages:
  base: !include .base.yaml
  bluetooth: !include .bluetooth.yaml
  i2c: !include .i2c.yaml
  bme280: !include .bme280.yaml
  bh1750: !include .bh1750.yaml
  ld2410: !include .ld2410.yaml

# Enable Home Assistant API
api:
  encryption:
    key: "VOTRE_CLE_API_ICI" # <-- Générée par ESPHome
